import type { NextPage } from 'next'
import Head from 'next/head'
import styles from "../styles/landing.module.css"
const Home: NextPage = () => {
  return (
    <div style={{ width: "100vw" }}>
      <Head>
        <title>Elwahid - Social Media for Couples</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={`${styles.header} ${styles.widthControlWrapper}`}>
        <div className={styles.widthControl}>
          <nav className={styles.nav}>
            <h2>Elwahid</h2>
            <div className={styles.headerButtonContainer}>
              <button className={`${styles.button} ${styles.buttonOutline}`}>Sign in</button>
              <button className={styles.button}>Sign up</button>
            </div>
          </nav>
        </div>
      </header>
      <main className={styles.widthControlWrapper}>
        <div className={styles.widthControl}>
          <div className={styles.heroContainer}>
            <div className={styles.heroHeading}>
              <h1 className={styles.headerLarge}>
                Social Media Made for
                <span>{' '}</span>
                <span>C</span><span>o</span><span>u</span><span>p</span>
                <span>l</span><span>e</span><span>s</span>
              </h1>
            </div>
            <div className={styles.headerCircle}></div>
            <div className={styles.headerCircle}></div>
          </div>
        </div>
      </main>
      <footer >

      </footer>
    </div>
  )
}

export default Home
