import type { NextPage } from 'next'
import Head from 'next/head'
import styles from "../styles/landing.module.css"
const Home: NextPage = () => {
  return (
    <div style={{ width: "100vw" }}>
      <Head>
        <title>Elwahid - Social Media for Couples</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={`${styles.header} ${styles.widthControlWrapper}`}>
        <div className={styles.widthControl}>
          <nav style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
            <h2>Elwahid</h2>
            <div className={styles.headerButtonContainer}>
              <button className={`${styles.button} ${styles.buttonOutline}`}>Sign in</button>
              <button className={styles.button}>Sign up</button>
            </div>
          </nav>
        </div>
      </header>

      <main >

      </main>

      <footer >

      </footer>
    </div>
  )
}

export default Home
